# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: adguard-config
# data:
#   AdGuardHome.yaml: |
#     bind_host: 0.0.0.0
#     bind_port: 3000
#     users:
#       - name: admin
#         password: $2y$05$yKmLnPOqrWQ5l4qS5Lz5cezj8zTih9Fue5FUjkYYa1LOgCTHwsQba

#     dns:
#       bind_hosts:
#         - 0.0.0.0
#       port: 53

#     schema_version: 32

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-work
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-conf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
apiVersion: v1
kind: Pod
metadata:
  name: adguard
  labels:
    app: adguard
spec:
  containers:
  - name: adguard
    image: docker.io/adguard/adguardhome:latest
    # command:
    #   - /bin/sh
    #   - -c
    #   - |
    #     cp /tmp/config/AdGuardHome.yaml /opt/adguardhome/conf/AdGuardHome.yaml && \
    #     /opt/adguardhome/AdGuardHome \
    #       --no-check-update \
    #       -c /opt/adguardhome/conf/AdGuardHome.yaml \
    #       -w /opt/adguardhome/work
    ports:
    - containerPort: 3000
      hostPort: 5300
      protocol: TCP
      name: admin
    - containerPort: 80
      hostPort: 8080
      protocol: TCP
      name: dns-over-http
    - containerPort: 53
      hostPort: 53
      protocol: UDP
      name: dns-udp
    - containerPort: 53
      hostPort: 53
      protocol: TCP
      name: dns-tcp
    volumeMounts:
    - name: work
      mountPath: /opt/adguardhome/work
    - name: conf
      mountPath: /opt/adguardhome/conf
    # - name: config
    #   mountPath: /tmp/config
    #   readOnly: true
    securityContext:
      seLinuxOptions:
        type: spc_t
  restartPolicy: OnFailure
  volumes:
  - name: work
    persistentVolumeClaim:
      claimName: adguard-work
  - name: conf
    persistentVolumeClaim:
      claimName: adguard-conf
  # - name: config
  #   configMap:
  #     name: adguard-config
